- name: Create Prometheus user
  user:
    name: prometheus
    system: yes
    shell: /sbin/nologin
    create_home: yes
    home: /var/lib/prometheus

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus binary
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: Copy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: reload prometheus

- name: Copy systemd service file
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Start and enable Prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: yes